# Generated by Django 6.0.1 on 2026-01-15 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Niveau')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Matière')),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('topic', models.CharField(max_length=200, verbose_name='Thème')),
                ('file', models.FileField(upload_to='exercises/', verbose_name='Fichier Exercice')),
                ('solution_file', models.FileField(blank=True, null=True, upload_to='solutions/', verbose_name='Fichier Corrigé')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Vues')),
                ('downloads', models.PositiveIntegerField(default=0, verbose_name='Téléchargements')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'TEACHER'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Enseignant')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.level', verbose_name='Niveau')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.subject', verbose_name='Matière')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('url', models.URLField(verbose_name='Lien YouTube')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.level', verbose_name='Niveau')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.subject', verbose_name='Matière')),
            ],
        ),
    ]
